export const emojis = [
    { name: 'sonrisa', code: '\u{1F604}' },
    { name: 'corazón', code: '\u{2764}' },
    { name: 'guiño', code: '\u{1F609}' },
    { name: 'gato sonriendo', code: '\u{1F638}' },
    { name: 'beso', code: '\u{1F617}' },
    { name: 'risa a carcajadas', code: '\u{1F602}' },
    { name: 'llanto de risa', code: '\u{1F606}' },
    { name: 'ojo guiñando', code: '\u{1F609}' },
    { name: 'lengua afuera', code: '\u{1F61B}' },
    { name: 'ojos de corazón', code: '\u{1F60D}' },
    { name: 'emoji con gafas', code: '\u{1F60E}' },
    { name: 'emoji sorprendido', code: '\u{1F62E}' },
    { name: 'emoji con corazón en los ojos', code: '\u{1F60D}' },
    { name: 'emoji pensativo', code: '\u{1F914}' },
    { name: 'emoji durmiendo', code: '\u{1F634}' },
    { name: 'emoji cansado', code: '\u{1F62B}' },
    { name: 'emoji enfadado', code: '\u{1F620}' },
    { name: 'emoji demonio', code: '\u{1F47F}' },
    { name: 'emoji asustado', code: '\u{1F628}' },
    { name: 'emoji de fuego', code: '\u{1F525}' },
    { name: 'emoji globo terráqueo', code: '\u{1F30D}' },
    { name: 'emoji sol', code: '\u{2600}' },
    { name: 'emoji luna', code: '\u{1F319}' },
    { name: 'emoji estrella fugaz', code: '\u{1F320}' },
    { name: 'emoji arco iris', code: '\u{1F308}' },
    { name: 'emoji unicornio', code: '\u{1F984}' },
    { name: 'emoji tortuga', code: '\u{1F422}' },
    { name: 'emoji elefante', code: '\u{1F418}' },
    { name: 'emoji pulpo', code: '\u{1F419}' },
    { name: 'emoji pingüino', code: '\u{1F427}' },
    { name: 'emoji cangrejo', code: '\u{1F980}' },
    { name: 'emoji pez', code: '\u{1F41F}' },
    { name: 'emoji delfín', code: '\u{1F42C}' },
    { name: 'emoji árbol', code: '\u{1F332}' },
    { name: 'emoji flor', code: '\u{1F33B}' },
    { name: 'emoji cactus', code: '\u{1F335}' },
    { name: 'emoji girasol', code: '\u{1F33B}' },
    { name: 'emoji hojas caídas', code: '\u{1F342}' },
    { name: 'emoji seta', code: '\u{1F344}' },
    { name: 'emoji bambú', code: '\u{1F38D}' },
    { name: 'emoji rosa', code: '\u{1F339}' },
    { name: 'emoji tulipán', code: '\u{1F337}' },
    { name: 'emoji mariquita', code: '\u{1F41E}' },
    { name: 'emoji mielbee', code: '\u{1F41D}' },
    { name: 'emoji caracol', code: '\u{1F40C}' },
    { name: 'emoji mariposa', code: '\u{1F98B}' },
    { name: 'emoji lombriz', code: '\u{1F41B}' },
    { name: 'emoji ave', code: '\u{1F426}' },
    { name: 'emoji loro', code: '\u{1F99C}' },
    { name: 'emoji pavo real', code: '\u{1F99F}' },
    { name: 'emoji mono', code: '\u{1F435}' },
    { name: 'emoji gorila', code: '\u{1F98D}' },
    { name: 'emoji elefante', code: '\u{1F418}' },
    { name: 'emoji ratón', code: '\u{1F42D}' },
    { name: 'emoji conejo', code: '\u{1F430}' },
    { name: 'emoji gato', code: '\u{1F431}' },
    { name: 'emoji león', code: '\u{1F981}' },
    { name: 'emoji tigre', code: '\u{1F42F}' },
    { name: 'emoji caballo', code: '\u{1F434}' },
    { name: 'emoji cabra', code: '\u{1F410}' },
    { name: 'emoji vaca', code: '\u{1F42E}' },
    { name: 'emoji cerdo', code: '\u{1F416}' },
    { name: 'emoji oveja', code: '\u{1F411}' },
    { name: 'emoji mono', code: '\u{1F435}' },
    { name: 'emoji pollo', code: '\u{1F414}' },
    { name: 'emoji pingüino', code: '\u{1F427}' },
    { name: 'emoji cerdo', code: '\u{1F416}' },
    { name: 'emoji tiburón', code: '\u{1F988}' },
    { name: 'emoji pulpo', code: '\u{1F419}' },
    { name: 'emoji pez payaso', code: '\u{1F420}' },
    { name: 'emoji ballena', code: '\u{1F433}' },
    { name: 'emoji árbol de navidad', code: '\u{1F384}' },
    { name: 'emoji regalo', code: '\u{1F381}' },
    { name: 'emoji campana', code: '\u{1F514}' },
    { name: 'emoji tarta', code: '\u{1F370}' },
    { name: 'emoji hamburguesa', code: '\u{1F354}' },
    { name: 'emoji pizza', code: '\u{1F355}' },
    { name: 'emoji taco', code: '\u{1F32E}' },
    { name: 'emoji sushi', code: '\u{1F363}' },
    { name: 'emoji helado', code: '\u{1F366}' },
    { name: 'emoji café', code: '\u{2615}' },
    { name: 'emoji refresco', code: '\u{1F379}' },
    { name: 'emoji cerveza', code: '\u{1F37A}' },
    { name: 'emoji vino', code: '\u{1F377}' },
    { name: 'emoji cóctel', code: '\u{1F378}' },
    { name: 'emoji copa', code: '\u{1F942}' },
    { name: 'emoji palomitas', code: '\u{1F37F}' },
    { name: 'emoji donut', code: '\u{1F369}' },
    { name: 'emoji pastel', code: '\u{1F382}' },
    { name: 'emoji galleta', code: '\u{1F36A}' },
    { name: 'emoji chocolate', code: '\u{1F36B}' },
    { name: 'emoji miel', code: '\u{1F36F}' },
    { name: 'emoji huevo', code: '\u{1F373}' },
    { name: 'emoji pollo', code: '\u{1F414}' },
    { name: 'emoji carne', code: '\u{1F356}' },
    { name: 'emoji pizza', code: '\u{1F355}' },
    { name: 'emoji frutas', code: '\u{1F34E}' },
    { name: 'emoji verduras', code: '\u{1F955}' },
    { name: 'emoji arroz', code: '\u{1F35A}' },
    { name: 'emoji pan', code: '\u{1F35E}' },
    { name: 'emoji hamburguesa', code: '\u{1F354}' },
    { name: 'emoji hot dog', code: '\u{1F32D}' },
    { name: 'emoji papas fritas', code: '\u{1F35F}' },
    { name: 'emoji helado', code: '\u{1F366}' },
    { name: 'emoji taza', code: '\u{1F375}' },
    { name: 'emoji tenedor y cuchillo', code: '\u{1F374}' },
    { name: 'emoji plato', code: '\u{1F37D}' },
    { name: 'emoji servilleta', code: '\u{1F374}' },
    { name: 'emoji botella de vino', code: '\u{1F377}' },
    { name: 'emoji copa', code: '\u{1F942}' },
    { name: 'emoji jarra de cerveza', code: '\u{1F37A}' },
    { name: 'emoji cóctel', code: '\u{1F378}' },
  ];